### PR TITLE
Preserve legacy clockless task queue user data

### PR DESCRIPTION
**Pull request by Shivs11**
## Summary

- allow incoming task queue user data to win when the current data is clockless
- keep clocked current data over clockless or older incoming data
- preserve legacy clockless payloads during replication while deferring semantic conflict merging

## Scope

This is a standalone backward-compatibility hotfix for task queue user data rows whose clocks were dropped by replication. The accepted payload remains clockless; this change prevents the payload from being discarded during another replication.

This PR does not copy non-nil incoming clocks; #12105 fixes that independently. It also does not implement semantic merging of conflicting task queue user data, which remains follow-up work.

## Testing

- `go test -tags test_dep ./service/matching -run 'TestMatchingEngine_.*_Suite/TestApplyTaskQueueUserDataReplicationEventAcceptsClocklessData' -count=1`
- `go test -tags test_dep ./service/matching -run '^TestMatchingEngine_(Classic|Pri|Fair)_Suite$/^TestApplyTaskQueueUserDataReplicationEventKeepsClockedCurrent$' -count=1`
- `go test -tags test_dep ./service/matching -count=1`
- `go vet -tags test_dep ./service/matching`

---

> [!NOTE]
> **Medium Risk**
> Changes last-writer-wins behavior for replicated task queue user data (versioning rules and per-type deployment/fairness state), which can affect multi-cluster consistency until fuller merge logic lands.
> 
> **Overview**
> Fixes **task queue user data replication** so legacy rows that lost their HLC clock are not overwritten by later replication events.
> 
> **`ApplyTaskQueueUserDataReplicationEvent`** now keeps **current** V2 rules and `PerType` only when the stored data has a **non-nil clock** and that clock beats the incoming one (or incoming is clockless). If **current** has no clock, **incoming** wins—so deployment/fairness payloads replicated without a clock are not dropped on the next apply.
> 
> This is a backward-compatibility hotfix; semantic merge for all clock combinations is left for follow-up. Tests cover clockless incoming replacing empty/different persisted data and clocked current beating clockless or older incoming data.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit b07e75a8cf52cd712c1fd56a650bf0c9a8f53b71. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: service/matching/matching_engine_test.go [hunk 1]
```diff
@@ -3005,6 +3005,142 @@ func (s *matchingEngineSuite) TestGetTaskQueueUserData_NoData() {
...
+			name:     "deployment data replaces persisted empty payload",
+			current:  &persistencespb.TaskQueueUserData{},
+			incoming: deploymentData,
+		},
+		{
+			name:     "fairness data replaces absent payload",
+			incoming: fairnessData,
+		},
+		{
+			name: "incoming data replaces different clockless payload",
```
Comment (Shivs11) [inline service/matching/matching_engine_test.go:3078]: this should not happen but no harm in testing it

**Review by ShahabT — APPROVED** [review]
